# docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    container_name: django_lab
    volumes:
      - .:/app
      - sqlite_data:/app/db
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=lab.settings
      - DEBUG=1
    env_file:
      - .env
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  sqlite_data: